<?php

namespace AppBundle\Repository;

/**
 * AgreementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgreementsRepository extends \Doctrine\ORM\EntityRepository
{
}
