<?php

namespace AppBundle\Repository;

/**
 * ComplementeritiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplementeritiesRepository extends \Doctrine\ORM\EntityRepository
{
}
