<?php

namespace AppBundle\Repository;

/**
 * CriteriaMatchingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriaMatchingRepository extends \Doctrine\ORM\EntityRepository
{
}
