<?php

namespace AppBundle\Repository;

/**
 * PersonalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalityRepository extends \Doctrine\ORM\EntityRepository
{
}
