<?php

namespace AppBundle\Repository;

/**
 * UserToWantToMeetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserToWantToMeetRepository extends \Doctrine\ORM\EntityRepository
{
}
