<?php

namespace AppBundle\Repository;

/**
 * UserAcceptationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAcceptationRepository extends \Doctrine\ORM\EntityRepository
{
}
