<?php

namespace AppBundle\Repository;

/**
 * WantToMeetForRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WantToMeetForRepository extends \Doctrine\ORM\EntityRepository
{
}
