<?php

namespace AppBundle\Repository;

/**
 * WhatLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhatLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
