users_index:
    path:     /
    defaults: { _controller: "AppBundle:Users:index" }
    methods:  [GET, POST]

users_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Users:show" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "AppBundle:Users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Users:delete" }
    methods:  [GET, POST]

change_password:
    path:     /changePassword
    defaults: { _controller: "AppBundle:Users:changePassword" }
    methods:  [GET, POST]

set_password:
    path:     /setPassword/{password}
    defaults: { _controller: "AppBundle:Users:setPassword" }
    methods:  [GET, POST]