AppBundle\Entity\City:
  type: entity
  table: city
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    cityName:
      type: string
      nullable: false
      options:
        fixed: false
      column: city_name
  lifecycleCallbacks: {  }
