AppBundle\Entity\Country:
  type: entity
  table: country
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    countryName:
      type: string
      nullable: false
      options:
        fixed: false
      column: country_name
  lifecycleCallbacks: {  }
