AppBundle\Entity\Films:
  type: entity
  table: films
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    filmName:
      type: string
      nullable: false
      options:
        fixed: false
      column: film_name
  lifecycleCallbacks: {  }
