AppBundle\Entity\WantToMeetFor:
  type: entity
  table: want_to_meet_for
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    meetFor:
      type: string
      nullable: false
      options:
        fixed: false
      column: meet_for
  lifecycleCallbacks: {  }